my_list = [1, 2, 3, 4, 5, 6]
print(my_list)
my_list.append ([10, 20, 30, 40])
print (my_list)
my_list.insert(1,15)
print (my_list)
my_list.extend([50, 60, 70])
print(my_list)
my_list.remove (my_list[-1])
print(my_list)
my_list.sort()
print(my_list)
sorted_list= sorted(my_list)
print(sorted_list)
index_30 = my_list.index(15)
print(index_30)

